Name of the project: “Dataset” para la Predicción de Insuficiencia Renal Aguda


Name of the members: Ana Sofía Orozco, Laura Sofía Chanchí, Paula Sofía Muñoz

Members' email: ansorozco@unicauca.edu.co, paulasofia@unicauca.edu.co, lchanchi@unicauca.edu.co

In [ ]:
# Ejemplos de tipos de datos
Dia_nacimiento = 22
Mes_nacimiento = 'septiembre'
Altura_cm = 175.70
Exito = True
print( type(Dia_nacimiento) , type(Mes_nacimiento) , type(Altura_cm) , type(Exito))

<class 'int'> <class 'str'> <class 'float'> <class 'bool'>


In the first example, the types of the different variables are being printed.

In [ ]:
#Ejemplo de Listas

colores = ["amarillo", "azul", "rojo", "verde", "morado", "negro"]
colores[1]
colores[0]
colores[-1]
colores[5]
colores[-3]
# Separar o cortar listas
colores[::]
colores[0:2]
colores[-2:-1]
colores[3:]
colores[:4]
colores[:]
colores[::-1]
colores[::-2]
colores[::2]
# Valores por defecto
colores[0:6:1]
colores[-1:-7:-1]

print("Sacar un solo valor: ",colores[1],colores[0],colores[-1],colores[5],colores[-3])

print("Valores por defecto: ", colores[::])

print("Intervalo 1:", colores[0:2])

print("Intervalo 2:", colores[-2:-1])

print("Intervalo 3:", colores[3:])

print("Intervalo 4:", colores[:4])

print("Intervalo 5:", colores[:])

print("Intervalo 6:", colores[::-1])

print("Intervalo 7:", colores[::-2])

print("Intervalo 8:", colores[::2])

print("Intervalo 9:", colores[0:6:1])

print("Intervalo 10:", colores[-1:-7:-1])


Sacar un solo valor:  azul amarillo negro negro verde
Valores por defecto:  ['amarillo', 'azul', 'rojo', 'verde', 'morado', 'negro']
Intervalo 1: ['amarillo', 'azul']
Intervalo 2: ['morado']
Intervalo 3: ['verde', 'morado', 'negro']
Intervalo 4: ['amarillo', 'azul', 'rojo', 'verde']
Intervalo 5: ['amarillo', 'azul', 'rojo', 'verde', 'morado', 'negro']
Intervalo 6: ['negro', 'morado', 'verde', 'rojo', 'azul', 'amarillo']
Intervalo 7: ['negro', 'verde', 'azul']
Intervalo 8: ['amarillo', 'rojo', 'morado']
Intervalo 9: ['amarillo', 'azul', 'rojo', 'verde', 'morado', 'negro']
Intervalo 10: ['negro', 'morado', 'verde', 'rojo', 'azul', 'amarillo']


Here we are learning how to work with lists, and how we can manipulate the start, end, and the step of the values. The value before the end is taken.

In [ ]:
# Añadir valores de una lista
colores.append("blanco")
colores

['amarillo', 'azul', 'verde', 'morado', 'negro', 'naranja', 'rosado', 'blanco']

Here we are learning: 1) how to add a value to a list and 2)the lists are dynamic

In [ ]:
colores = colores + [ "naranja" , "rosado"]
colores

['amarillo',
 'azul',
 'verde',
 'morado',
 'negro',
 'naranja',
 'rosado',
 'blanco',
 'naranja',
 'rosado']

This is another way to add values in case that more than one is added at the same time

In [ ]:
#cambiar valores en una lista

colores [0:2] = [ "fucsia" , "gris" ]
colores


['fucsia',
 'gris',
 'verde',
 'morado',
 'negro',
 'naranja',
 'rosado',
 'blanco',
 'naranja',
 'rosado']

Here, through a selection of intervals, several of the values in a list are being changed

In [ ]:
# Borrar valores de una lista
colores.remove("rojo")
colores

['amarillo', 'azul', 'verde', 'morado', 'negro']

Here an element is being removed from a list by its name

In [ ]:
#Calificaciones de series con listas
series = ["Game of Thrones", "Breaking Bad", "Dark"]
calificaciones = [8.4, 7.2, 9.3]
seleccion_indice_serie = series.index("Dark")
print(calificaciones[seleccion_indice_serie])

9.3


Here two lists are being created, then the index of an element of the first list is being found by its name and after this, this index is used to search in the second list for the desired element.

In [ ]:
calificaciones = {

  "Game of Thrones": 8.4,
  "Breaking Bad": 7.2,
  "Dark" : 9.3
}
print(calificaciones["Dark"])

9.3


Here a dictionary is being created with the key, value format. 3 keys and values added, and one of these is being printed

In [ ]:
calificaciones[ "La Casa de Papel" ] = 8.0
print(calificaciones)
calificaciones[ "Game of Thrones" ] = 8.8
print(calificaciones)
del(calificaciones["Dark"])
print(calificaciones)

{'Game of Thrones': 8.4, 'Breaking Bad': 7.2, 'Dark': 9.3, 'La Casa de Papel': 8.0}
{'Game of Thrones': 8.8, 'Breaking Bad': 7.2, 'Dark': 9.3, 'La Casa de Papel': 8.0}
{'Game of Thrones': 8.8, 'Breaking Bad': 7.2, 'La Casa de Papel': 8.0}


Here, in the first instance, a new element is being added to the dictionary, then a value of the dictionary is being changed by using its key and finally an element is being deleted using its key.

In [ ]:
print("Game of Thrones" in calificaciones)

True


Here a key is being searched within the dictionary, resulting in true if it is found and false if not.

In [ ]:
def es_primo(n):
  if n <= 1:
    return False
  elif n <= 3:
    return True
  elif n % 2 == 0 or n % 3 == 0:
    return False
  numero_actual = 5
  while numero_actual * numero_actual <= n:
    if n % numero_actual == 0 or n % (numero_actual + 2) == 0:
      return False
    numero_actual = numero_actual + 6
  return True

First the function called es_primo is being defined which will receive a number that will be called n, then it checks, every number less than or equal to 1 is not prime so it will return false, in the second if it will check if the number is two , if so it will be returned true because it is a prime number, otherwise the module of the number will be checked against 2 or 3, if the result is 0 it means that the number is divisible by one of these two, therefore He is not a prime. If it did not enter any of the previous ifs, it means that now it will be compared with the next prime, which is 5. From this moment on, a while will be used since the following primes follow the pattern of interleaving each other every certain interval. . First, it is verified that the current number (which will be in charge of verifying the desired number) multiplied by itself is less than or equal to the number to be verified. If this is correct, the module of the desired one is verified with the current one and with the current one + 2; If correct, it returns false and if not, it increases the current number by 6. This process is repeated until the verification condition is no longer met and in that case true will be returned.

In [ ]:
#METHODS (is available for an object depending on its type, such as int float etc.)

# Methods for text strings (str)
text = "Electiva: TIC en salud"
text.upper()  # upper function--> Output all capitalized text
text.lower()  # Lower function--> Output all lower case text
text.capitalize() # Capitalize function--> The first letter is capitalized and the others in lower case, as in a conventional text.
print (text.upper() )
print (text.lower() )
print (text.capitalize())

ELECTIVA: TIC EN SALUD
electiva: tic en salud
Electiva: tic en salud


In [ ]:
#Methods for lists
numeros = [1, 3, 5, 2, 9, 8, 11] #Declare the list
numeros.reverse() # Pulls the list backwards (-1...0)
print("Resultado del reverse:",numeros)
numeros.sort() # Organize the numbers from smallest to largest
print("Resultado del Sort:",numeros)

Resultado del reverse: [11, 8, 9, 2, 5, 3, 1]
Resultado del Sort: [1, 2, 3, 5, 8, 9, 11]


In [ ]:
#Methods for dictionaries
calificaciones = {       # Declare the Dictionary, with its key:value
"Game of Thrones": 8.4,
"Breaking Bad": 7.2,
"Dark" : 9.3
}
print(calificaciones.keys())   #Get the keys from the dictionary
print(calificaciones.values()) #Take the values out of the dictionary
print(calificaciones.items())  #Draw all dictionary items with their key: value

dict_keys(['Game of Thrones', 'Breaking Bad', 'Dark'])
dict_values([8.4, 7.2, 9.3])
dict_items([('Game of Thrones', 8.4), ('Breaking Bad', 7.2), ('Dark', 9.3)])


In [ ]:
#Method for each type of object
numeros = [12, 20, 35, 28, 8, 46]
texto = "Electiva: TIC en salud"  # Lists are declared: numbers and text

#Position
numeros.index(8) #Draw the position that number 8 is occupying in the list of numbers (list of int)
texto.index("a") #Draw the position that number 8 is occupying in the list of numbers (list of int)

#Count
numeros.count(20) # Count how many 20s there are
texto.count("e")   # Count the number of e's (miniscules) that are present.

print('Resultados de Posición para la lista numeros:', numeros.index(8))
print('Resultados de Posición para la lista texto:', texto.index("a") )
print('Resultados de Contar para la lista numeros:', numeros.count(20) )
print('Resultados de Contar para la lista texto:', texto.count("e") )

Resultados de Posición para la lista numeros: 4
Resultados de Posición para la lista texto: 7
Resultados de Contar para la lista numeros: 1
Resultados de Contar para la lista texto: 2


In [ ]:
#PACKAGES (Collection of modules in directories, modules--> Specify functions, methods )

  #Statements
import numpy #Numpy package is imported
numeros = numpy.array([2, 3, 19, 14, 6, 18, 0]) #An array is created from the list.

print(numeros)

[ 2  3 19 14  6 18  0]


In [ ]:
  #Statement with an alias
import numpy as np     # np is an alias for the NumPy package
numeros = np.array([2, 3, 19, 14, 6, 18, 0]) #The array is declared with the alias np
numeros = numpy.array([3, 4, 20, 15, 7, 19, 0]) # Will throw error because the numpy package is np

print (numeros)


[ 3  4 20 15  7 19  0]


In [ ]:
#Import submodules of a package
import matplotlib.pyplot as plt  #from the matplotlib package extract the pyplot submodule and add the plt alias to it

In [ ]:
#Import a function from a package
from numpy import array # I import from the numpy package the array function
numeros = array([3, 4, 20, 15, 7, 19, 0]) # The array is declared
numeros = numpy.array([3, 4, 20, 15, 7, 19, 0]) # Error--> The numpy package is not defined, only the array function is not defined.

type(numeros)  #numpy.ndarray -->n-dimensional matrix

numpy.ndarray

In [ ]:
#NumPy PACKAGE USAGE (requires only one type for the array)

# ONE-DIMENSIONAL ARRAYS
    # NumPy Array - Type Conversion
import numpy as np
x= np.array([False, 36, "Electiva: TIC en salud"]) # different types: boolean, int, str
y= np.array([False, 36], dtype = int) # elements false and 36 become int
z=np.array([False, 36, 67.93], dtype = float) #3 elements become float

print (x)
print(y)
print(z)
#We can see that it is easy to make a conversion between booleans, integers and float because it reads them as a number but in the cases of a str:


#Invalid Conversion
w= np.array([False, 36, "Electiva: TIC en salud"], dtype = float)# Search from a str to a float --> CAN NOT
print(w)

['False' '36' 'Electiva: TIC en salud']
[ 0 36]
[ 0.   36.   67.93]


ValueError: ignored

In [ ]:
   # Numpy operations
    # Operators on NumPy arrays
a= np.array([33, 45, 58]) + 1  #1 is added to the whole array
b= np.array([25, 3, 40]) * 2
c= np.array([44, 20, 70]) / 2
d= np.array([4, 5, 6]) * np.array([10, 20, 30]) # The elements of each array are multiplied (they have equal size).
e= np.array([4, 5, 6]) - np.array([10, 20, 30])

print('Resultado de la suma:', a)
print('Resultado de la multiplicación:',b)
print('Resultado de la división:',c)
print('Resultado de la multiplicación de arrays:',d)
print('Resultado de la resta de arrays:',e)

Resultado de la suma: [34 46 59]
Resultado de la multiplicación: [50  6 80]
Resultado de la división: [22. 10. 35.]
Resultado de la multiplicación de arrays: [ 40 100 180]
Resultado de la resta de arrays: [ -6 -15 -24]


In [ ]:
#2-DIMENSIONAL MATRIXES (numpy.ndarray.)-->Ndarray stands for n-dimensional array.
 #Two-dimensional arrays
numeros = np.array([
[2, 4, 6],
[1, 3, 5],
[5, 7, 9],
[6, 8, 10]
])               #4 rows * 3 columns matrix declared

# If I wanted to extract an element from that array:
a =numeros[2, 1]  # row 2 column 1, counting from 0 the first array
b=numeros[-1, 0] # last row, first column
c= numeros[0]
d= numeros[:, 0] #All the row with the first column
e= numeros[0:3, 2] # Intersection from row 0 to row 3 with the last column
f=numeros[1:3, 1:3]

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

7
6
[2 4 6]
[2 1 5 6]
[6 5 9]
[[3 5]
 [7 9]]


In [ ]:
# To know the dimensions of each matrix and how many elements are in them (shape)
  # Attribute 'shape' of NumPy
numeros = np.array([
[2, 4, 6],
[1, 3, 5],
[5, 7, 9],
[6, 8, 10],
[11, 13, 15]
])
print( numeros.shape ) #Result 5 rows*3columns

(5, 3)


In [ ]:
#Data statistics with Numpy
horas_aprendizaje = [1, 2, 6, 4, 10]
notas = [3, 4, 6, 5, 8]

a= np.mean(horas_aprendizaje)   # Mean method--> Average the mean.
b= np.median(horas_aprendizaje) # Median method -->Draws the median
c=np.std(horas_aprendizaje)     # Method std --> Get the standard deviation
d= np.corrcoef(horas_aprendizaje, notas) # Corrcoef method--> Output the correlation matrix between the two lists.

print('El promedio es:',a)
print('La mediana es:',b)
print('La desviación estándar es:',c)
print('La matriz de correlación entre horas y notas es:',d)

El promedio es: 4.6
La mediana es: 4.0
La desviación estándar es: 3.2
La matriz de correlación entre horas y notas es: [[1.         0.99537041]
 [0.99537041 1.        ]]


In [ ]:
#CONTROL STRUCTURE
#FOR cycles
numeros = [13, 15, 18, 20, 23] #Declare the list
for numero in numeros:         #For element in list
  print(numero)

# A block of n number of times:
for numero in range(0,10) :    #Starts from 0 to n-1 =9
  print(f"numero = {numero}")

13
15
18
20
23
numero = 0
numero = 1
numero = 2
numero = 3
numero = 4
numero = 5
numero = 6
numero = 7
numero = 8
numero = 9


* Condicional IF -> when it's fulfilled, it executes a block
* elif -> Abbreviation of else if


In [ ]:

#Variable Definition

habitacion="comedor"
area=160.0

#conditional block construction

if habitacion=="comedor": # Comparison
  print("Buscar en el comedor")
elif habitacion=="cocina": #If the 'if' condition is not met, it enters here. -> sino si
  print("Buscar en la cocina")
else: #if the conditions are not met -> else -> last option
  print("Buscar en el resto de la casa")

#conditional block construction for area

if area > 160 : #Test if the area is greater than the value 160
  print("Lugar amplio")
elif area > 100:
  print ("Espacio Normal")
else:
  print("Lugar pequeño")

Buscar en el comedor
Espacio Normal


While Loop

* It runs as long as the condition is initially true; otherwise, it moves to the next group of statements.
* Any number diffrente from 0 is true, if it's zero, it's false.
* The condition can also be a list or a sequence; if it's empty, it's false



In [ ]:
#List iteration

vocales=["a","e","i","o","u"]

while vocales:
  print(vocales.pop(0)) #Remove and return the first element of the list


a
e
i
o
u


In [ ]:
vocales #It should appear empty due to the pop function also deletes the elements.

[]

In [ ]:
#example of a while loop: While x is different from 1, the printing is done

x=3

while x != 1:
  print(f"x={x}")

  if x % 2 ==0 : # check if it's even
    x=x//2 #Divide and round down to the nearest integer
  else:
    x=3*x+1 #It happens if the number is odd


x=3
x=10
x=5
x=16
x=8
x=4
x=2


Lambda functions

Allows to define very simple anonymous functions, its return value is the result of evaluating a single expression.

In [ ]:
#lambda definitio

funcion_lambda= lambda x,y: x+y
funcion_lambda(2,3) # It receives the values of x and y in order to execute the operation.

5

Filter Function: Allows filtering from a list or iterator using a conditional function. Lambda functions are useful in these cases.



In [ ]:
a=[0,1,-1,-2,3,-4,5,6,7]
resultado= filter (lambda x: x>0, a)

for valor in resultado:
  print(valor)

1
3
5
6
7


Map Function: It is similar to the filter function, but instead of applying a condition, it applies a function to all elements of the list and returns an iterable of type map.

In [ ]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]

list(map(lambda x,y : x*y, a,b)) # It also recieves the lists to which the operation is applied.

[6, 14, 24, 36, 50]

List comprehensions: Provide a simple way to create a list based on iterables. Elements from the iterable can be conditionally included in a new list and also transformed.

In [ ]:
numeros=[1,2,3,4,5]
cuadrados=[numero**2 for numero in numeros] # Creates a new list with the square operation of each element from a previous list, iterating to create the new one.
print(cuadrados)

[1, 4, 9, 16, 25]


In [ ]:
cuadrados=[numero**2 for numero in numeros if numero >2] # Perform the same process as the previous one, but check a condition before adding the element to the new list
print(cuadrados)

[9, 16, 25]


List comprehensions vs for loops: List comprehensions are often more efficient than for loops because they are written in a single line. However, it's important to note that "Every list comprehension can be rewritten as a for loop, but not all for loops can be rewritten as a list comprehension.

In [ ]:
nuemeros=[1,2,3,4]
cuadrados=[]
for numero in numeros: # Loop to iterate through the numbers in the list
  if numero>2:# Conditional that checks if the current element is greater than 2
    cuadrados.append(numero**2) # if it satisfies the condition, add the current element squared to the 'cuadrados' list.
print(cuadrados)

[9, 16, 25]



List comprehensions anidadas: If we place a list in the output expression of another list, you will obtain a matrix as a result.

In [ ]:
matriz=[[item for item in range(5)] for fila in range(3)]#Iterate through the list with items from 0 to 4, then iterate this list 3 times (rows), creating a matrix
print(matriz)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
